"""add email password token

Revision ID: 7178c9f51d6f
Revises: c5a4f4be4b14
Create Date: 2025-12-17 04:36:42.142136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7178c9f51d6f'
down_revision: Union[str, Sequence[str], None] = 'c5a4f4be4b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_password_reset_tokens_id'), 'email_password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_password_reset_tokens_token'), 'email_password_reset_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_password_reset_tokens_token'), table_name='email_password_reset_tokens')
    op.drop_index(op.f('ix_email_password_reset_tokens_id'), table_name='email_password_reset_tokens')
    op.drop_table('email_password_reset_tokens')
    # ### end Alembic commands ###
