"""add last_password_reset_sent_at to users

Revision ID: f408b90404eb
Revises: 7178c9f51d6f
Create Date: 2025-12-17 05:08:02.505360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f408b90404eb'
down_revision: Union[str, Sequence[str], None] = '7178c9f51d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_password_reset_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset_sent_at')
    # ### end Alembic commands ###
